- docker/run-server.sh
- setup.py
- superset-frontend/webpack.config.js
- superset/config.py
- superset/stats_logger.py
1. Added Script to pull AWS Secrets for Careem Insights
2. Changed Gunicorn config for Async recommendation as per Apache Superset 
3. Installed additional Python Packages
4. Commented TypeScript checks for Dev
5. Enabled StastD for Metrics
> Feat: Dev Configurations

- Dockerfile
- docker/run-server.sh
- secrets.sh
- superset-frontend/package.json
- superset-frontend/src/views/CRUD/flashManagement/components/FlashExtendTTl/FlashExtendTTl.tsx
- superset-frontend/src/views/CRUD/flashManagement/components/FlashGrid/FlashList.tsx
- superset-frontend/src/views/CRUD/flashManagement/components/FlashOwnership/FlashOwnership.tsx
- superset-frontend/src/views/CRUD/flashManagement/components/FlashQuery/FlashQuery.tsx
- superset-frontend/src/views/CRUD/flashManagement/components/FlashSchedule/FlashSchedule.tsx
- superset-frontend/src/views/CRUD/flashManagement/constants.ts
- superset-frontend/src/views/CRUD/flashManagement/enums.ts
- superset-frontend/src/views/CRUD/flashManagement/services/flash.service.ts
- superset-frontend/src/views/CRUD/flashManagement/types.ts
- superset/config.py
- superset/initialization/__init__.py
Flash Management Sql Query Updating
> feat(BDP-4652): Flash Sql Query Updation

- superset-frontend/src/views/CRUD/flash/components/FlashExtendTTl/FlashExtendTTl.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashGrid/FlashList.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashOwnership/FlashOwnership.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashQuery/FlashQuery.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashSchedule/FlashSchedule.tsx
- superset-frontend/src/views/CRUD/hooks.ts
1- Toasters Addition in Updating of Flash
2- Database Name mapping in Flash Management Grid
3- Adding Spaces in Flash Type enums
> feat(changes) : Flash Module Changes (minor)

- superset-frontend/src/components/ListView/Filters/Date.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashCreationButton/FlashCreationButton.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashOwnership/FlashOwnership.tsx
- superset/config.py
1- Validation on email address to accepts (careem.com) only.
2- Disabling or validating schedule start time in Management as well as Creation
3- Cosmetic UI Changes
> feat(BDP-4745): Flash Module Changes

- superset-frontend/src/SqlLab/actions/sqlLab.js
- superset-frontend/src/SqlLab/components/SqlEditor/index.jsx
- superset-frontend/src/views/CRUD/flash/components/FlashCreationButton/FlashCreationButton.tsx
1. SQL query issue when FLASH Object created. 
2. FLASH fields are not reset if API call is success
> Fix(query): Sql Query Modification and Reset

- superset-frontend/src/SqlLab/actions/sqlLab.js
- superset-frontend/src/SqlLab/components/SqlEditor/SqlEditor.test.jsx
- superset-frontend/src/views/CRUD/flash/components/FlashCreationButton/FlashCreationButton.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashExtendTTl/FlashExtendTTl.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashOwnership/FlashOwnership.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashSchedule/FlashSchedule.tsx
- superset-frontend/src/views/CRUD/flash/types.ts
- superset/config.py
- superset/connectors/sqla/models.py
1- SQL query issue when FLASH Object created.
2- FLASH fields are not reset if API call is success.
3- Adding regex to specific properties: domain, service, dataset - should not start with _ or end in it and shouldn’t have double _ in it.
4- Catch Flash Exceptions and showcase in Toaster on Careem Insights.
5- Field Error messages should have a smaller font .
> feat(BDP-4787): Flash Integration Changes

- superset-frontend/src/SqlLab/actions/sqlLab.js
> Fix(toaster): Toaster Duplication Issue

- superset-frontend/src/views/CRUD/flash/components/FlashCreationButton/FlashCreationButton.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashQuery/FlashQuery.tsx
- superset/config.py
Schedule Start Time should be greater than now
> fix : Schedule Start Time should be greater than now

- superset-frontend/src/SqlLab/components/SqlEditor/index.jsx
- superset-frontend/src/views/CRUD/flash/components/FlashCreationButton/FlashCreationButton.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashSchedule/FlashSchedule.tsx
1- While updating flash date format changes to 24 hour format
> fix: Date 24 hour format issue

- Dockerfile.internal
- superset/connectors/sqla/models.py
> Date Filter (Fix)

- superset-frontend/src/SqlLab/actions/sqlLab.js
- superset-frontend/src/SqlLab/components/SqlEditor/index.jsx
- superset-frontend/src/explore/components/ExploreChartHeader/index.jsx
- superset-frontend/src/views/CRUD/flash/components/FlashCreationButton/FlashCreationButton.tsx
- superset/config.py
1- Reseting and closing form only if flash has been created successfully.
2- Email Validation Pattern changed
> fix: Reseting and closing form 

- superset-frontend/src/utils/commonHelper.ts
- superset-frontend/src/views/CRUD/flash/components/FlashExtendTTl/FlashExtendTTl.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashGrid/FlashList.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashQuery/FlashQuery.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashView/FlashView.tsx
- superset-frontend/src/views/CRUD/flash/types.ts
feat(BDP-4801): View Flash Object Information
1- Action button visibility on Flash Management Module.
2- Opening draggable View Flash Modal on action trigger
3- Displaying all the flash object details briefly
> feat(BDP-4801): View Flash Object Information

- superset-frontend/src/views/CRUD/alert/AlertReportModal.tsx
- superset-frontend/src/views/CRUD/alert/components/NotificationMethod.tsx
1- Add validation for email in Alerts & Reports (@careem.com & @ext.careem.com)
> feat: Email Validation in Alerts & Reports

- superset-frontend/src/views/CRUD/alert/AlertReportModal.tsx
- superset-frontend/src/views/CRUD/alert/components/NotificationMethod.tsx
1- For Slack method, Email validation was triggering
> fix(alerts): Delivery Method for Slack

- superset-frontend/package.json
- superset-frontend/src/views/CRUD/flash/constants.ts
1- Flash Status 'MarkedForDeletion' Added in flash management
2- Insights version updated to 1.0.0
> feat(DNA-603): Flash Status and version updation

- superset/views/database/forms.py
Dynamic Helper Text added in size, rows limit and pattern
> fix: Dynamic helper text

- superset-frontend/src/views/CRUD/data/dataset/DatasetList.tsx
- superset/views/base.py
- The users can view the datasets created by other users, given that it has been created using data from the DB connection the user has access to.
- Only the owner of the dataset can access additional functionality such as DELETING the dataset, and can EDIT it.
> feat(DNA-705): Customisation of dataset access

- requirements/development.txt
- superset/db_engine_specs/pinot.py
DNA943 Chart metrix pinot fix
* fix the metric skewness by enabling the SELECT alias
* add dev support for the pinotdb
> DNA943 Chart metrix pinot fix

- superset-frontend/src/views/CRUD/chart/ChartList.tsx
- superset/charts/filters.py
1- Users can view charts created by other users.
2- Users can create charts using datasets added by other users.
provided they have same database role
> feat(DNA-1071): Customisation access level in Charts

- superset/config.py
> feat: Chart Axes Enabled

- superset-frontend/src/views/CRUD/flash/components/FlashGrid/FlashList.tsx
- superset-frontend/src/views/CRUD/flash/constants.ts
Adding Status 'Materialized_Failed' in status filter of flash page.
Adding 'Last_Refresh_Time' as a column in Flash Grid
> feat(DNA-1210): Adding status and last refresh time in flash grid

- requirements/base.txt
- superset-frontend/src/SqlLab/components/ResultSet/index.tsx
- superset-frontend/src/SqlLab/components/SouthPane/index.tsx
- superset-frontend/src/profile/components/fixtures.tsx
- superset/config.py
- superset/security/manager.py
- superset/utils/excel.py
- superset/views/base.py
- superset/views/core.py
Users can download dataset in excel format
> feat(DNA-903): Download Excel Functionality in Sql Lab

- superset-frontend/package-lock.json
- superset-frontend/package.json
- superset-frontend/src/views/CRUD/flash/components/FlashAuditLogs/FlashAuditLogs.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashGrid/FlashList.tsx
- superset-frontend/src/views/CRUD/flash/services/flash.service.ts
- superset-frontend/src/views/CRUD/flash/types.ts
- superset-frontend/src/views/CRUD/hooks.ts
- superset-frontend/src/views/routes.tsx
- superset/views/flash/views.py
> feat (DNA-1206): Audit Logs Screen in Flash

- docs/static/resources/openapi.json
- superset-frontend/src/views/CRUD/alert/AlertReportModal.tsx
- superset-frontend/src/views/CRUD/alert/types.ts
- superset/charts/filters.py
- superset/config.py
- superset/migrations/versions/2022-12-23_21-25_b060a1b53a06_add_msg_content_to_report_schedule.py
- superset/reports/api.py
- superset/reports/commands/create.py
- superset/reports/commands/execute.py
- superset/reports/models.py
- superset/reports/notifications/base.py
- superset/reports/notifications/email.py
- superset/reports/notifications/slack.py
- superset/reports/schemas.py
- superset/utils/core.py
- superset/views/base.py
- tests/integration_tests/reports/api_tests.py
- tests/integration_tests/reports/commands/execute_dashboard_report_tests.py
- tests/integration_tests/reports/utils.py
- tests/unit_tests/notifications/email_tests.py
> feat(DNA-1558): Alerts & Reports v2

- docs/static/resources/openapi.json
- superset-frontend/src/views/CRUD/alert/AlertReportModal.tsx
- superset-frontend/src/views/CRUD/alert/types.ts
- superset/charts/filters.py
- superset/config.py
- superset/migrations/versions/2022-12-23_21-25_b060a1b53a06_add_msg_content_to_report_schedule.py
- superset/reports/api.py
- superset/reports/commands/create.py
- superset/reports/commands/execute.py
- superset/reports/models.py
- superset/reports/notifications/base.py
- superset/reports/notifications/email.py
- superset/reports/notifications/slack.py
- superset/reports/schemas.py
- superset/utils/core.py
- superset/views/base.py
- tests/integration_tests/reports/api_tests.py
- tests/integration_tests/reports/commands/execute_dashboard_report_tests.py
- tests/integration_tests/reports/utils.py
- tests/unit_tests/notifications/email_tests.py
> feat(DNA-381): Text message content addition in Alerts and Reports

- superset-frontend/src/views/CRUD/alert/AlertReportModal.tsx
> feat(DNA-1726,1727): Log Retention and Working Timeout in Alerts & Reports

- superset-frontend/src/views/CRUD/alert/AlertReportModal.tsx
> fix: Alerts Report Max Timeout Issue

- superset-frontend/src/views/CRUD/flash/components/FlashCreationButton/FlashCreationButton.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashQuery/FlashQuery.tsx
- superset-frontend/src/views/CRUD/flash/constants.ts
- superset-frontend/src/views/CRUD/flash/services/flash.service.ts
- superset-frontend/src/views/CRUD/hooks.ts
> fix(DNA-1875): Generic Error Messages

- superset-frontend/src/components/ConfirmationModal/index.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashGrid/FlashList.tsx
- superset-frontend/src/views/CRUD/flash/services/flash.service.ts
> feat(DNA-1716): Flash Recovery

- superset-frontend/src/views/CRUD/flash/components/FlashExtendTTl/FlashExtendTTl.tsx
- superset-frontend/src/views/CRUD/flash/types.ts
- superset/config.py
> Revert "feat(DNA-1715): update flash type"

- superset/reports/commands/execute.py
- superset/reports/notifications/base.py
- superset/reports/notifications/email.py
- superset/reports/notifications/slack.py
- superset/views/explore_response.py
- tests/integration_tests/celery_tests.py
- tests/unit_tests/jinja_context_test.py
> feat(DNA-1937,1938): Alert & Reports Template Changes

- superset/reports/commands/execute.py
- superset/reports/notifications/base.py
- superset/reports/notifications/slack.py
- superset/views/explore_response.py
- tests/integration_tests/celery_tests.py
- tests/unit_tests/jinja_context_test.py
> feat(DNA-1938): Notification type and Indentation

- superset-frontend/src/components/ListView/ListView.tsx
- superset-frontend/src/components/TableCollection/index.tsx
- superset-frontend/src/views/CRUD/data/components/SyntaxHighlighterCopy/index.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashAuditLogs/ErrorStackTrace.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashAuditLogs/FlashAuditLogs.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashAuditLogs/JsonDiff.tsx
- superset-frontend/src/views/CRUD/flash/types.ts
> feat (DNA-2788): Flash Audit Log Changes

- superset-frontend/src/views/CRUD/dashboard/DashboardList.tsx
> feat(DNA-3221): Disabled actions for non-owners

- superset-frontend/src/views/CRUD/flash/components/FlashCreationButton/FlashCreationButton.tsx
**BEFORE SCREENSHOT**
**AFTER SCREENSHOT:**
> feat(DNA-3277): Removing Schedule Start Time Validation in Flash Creation

- superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/index.jsx
- superset-frontend/src/dashboard/components/Header/index.jsx
**FOR OTHER USERS:**
**FOR ADMIN:**
> feat(DNA-3272): Auto Refresh in dashboard enabled for admin

- superset-frontend/src/views/CRUD/alert/AlertReportModal.tsx
- superset-frontend/src/views/CRUD/alert/constants.ts
- superset-frontend/src/views/CRUD/alert/helper.ts
Possible cases to implement:
CRON SCHEDULE:
The max working timeout should be 5 mins.
> feat(DNA-3591): Working Timeout Validation on Alerts and Reports

- superset-frontend/src/views/CRUD/flash/components/FlashGrid/FlashList.test.ts
- superset-frontend/src/views/CRUD/flash/components/FlashGrid/FlashList.tsx
- superset-frontend/src/views/CRUD/flash/services/flash.service.ts
> feat(DNA-3496): Set the Flash Status dropdown in filter to Dynamic

- superset-frontend/src/components/Initials/index.tsx
- superset-frontend/src/utils/commonHelper.ts
- superset-frontend/src/views/CRUD/flash/components/FlashAuditLogs/FlashAuditLogs.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashGrid/FlashList.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashView/FlashView.tsx
- superset-frontend/src/views/CRUD/flash/components/helper.ts
- superset-frontend/src/views/CRUD/flash/constants.ts
**BEFORE:**
src="https://github.com/careem/superset/assets/106157603/fa45d5b4-b9f7-464f-801f-0819158f9f99">
**AFTER:**
> feat(DNA-4328) : Flash UI Cosmetic Changes

- superset-frontend/src/utils/commonHelper.ts
- superset-frontend/src/views/CRUD/flash/components/FlashAuditLogs/FlashAuditLogs.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashGrid/FlashList.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashView/FlashView.tsx
- Adding local date format to TTL
- Adding local datetime format with fallback to other datetime properties such as Schedule Start Time, CreatedAt, LastRefreshTime, nextRefreshTime, updateAt etc.
**BEFORE:**
**AFTER:**
> feat(DNA-2416): Fix the timestamp in flash UI

- superset-frontend/src/views/CRUD/flash/components/FlashAuditLogs/FlashAuditLogs.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashExtendTTl/FlashExtendTTl.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashGrid/FlashList.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashOwnership/FlashOwnership.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashQuery/FlashQuery.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashSchedule/FlashSchedule.tsx
- superset-frontend/src/views/CRUD/flash/components/FlashType/FlashType.test.jsx
- superset-frontend/src/views/CRUD/flash/components/FlashType/FlashType.tsx
- superset-frontend/src/views/CRUD/flash/types.ts
> feat(DNA-4398): updateBy key added in the required apis

- superset/config.py
- superset/sql_validators/__init__.py
- superset/sql_validators/my_sql_db.py
- superset/sql_validators/trino_db.py
- tests/integration_tests/sql_validator_tests.py
> ref(DNA-4425): Refactor Alerts Query Validaiton

- superset-frontend/src/SqlLab/components/SaveDatasetModal/index.tsx
- superset/sql_validators/trino_db.py
> fix(DNA-XXX): explain type validate added for trino gateway

- .github/workflows/GitLeaks.yml
> Revert "[MISC] Delete .github/workflows/GitLeaks.yml"
